<a href="https://colab.research.google.com/github/Rahulraj31/Fake-News-LSTM/blob/main/Fake_News_Classifier_Using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Fake News Classifier Using LSTM


Dataset: https://www.kaggle.com/c/fake-news/data#

In [1]:
import zipfile

local_zip = '/content/drive/MyDrive/Colab Notebooks/fake-news.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content')
zip_ref.close()

In [2]:
import pandas as pd
df= pd.read_csv("/content/train.csv")

In [3]:
df.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

**1: unreliable**<br>

**0: reliable**

In [4]:
df.shape

(20800, 5)

In [5]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [6]:
df=df.dropna()

In [7]:
# Get the Independent and Dependent Features
X=df.drop('label',axis=1)
Y=df['label']

In [8]:
X.shape,Y.shape

((18285, 4), (18285,))

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences  #for proper same size input to embedding layer, same as widow in genshim
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense,Dropout

In [10]:
# vocabulary size
voc_size =5000

## One hot Representation


In [11]:
messages=X.copy()

In [12]:
messages.reset_index(inplace=True)

In [13]:
import nltk
import re
from nltk.corpus import stopwords

In [14]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:
# Dataset preprocessing
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()
corpus = []
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages["title"][i]) #substitute everthing with blank apart from letters a-z and A-Z in title
  
  review =review.lower() #convert to lower case
  
  review=review.split() 

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')] #stems words no present in stopword
  review = ' '.join(review) #combining list of words to a list of sentences
  corpus.append(review)
  

In [16]:
onehot_rep= [one_hot(words,voc_size) for words in corpus]

In [17]:
# one hot for first 5 sentences
onehot_rep[0:5]

[[4253, 2140, 2357, 4180, 1491, 1031, 1996, 704, 1182, 1795],
 [3138, 4162, 751, 1246, 786, 325, 2901],
 [276, 4144, 1042, 565],
 [4315, 319, 4977, 976, 1679, 1054],
 [3241, 786, 3480, 3118, 2022, 356, 786, 3111, 1051, 3416]]

## Embedding Representation

In [18]:
sent_length =20
embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  704 1182 1795]
 [   0    0    0 ...  786  325 2901]
 [   0    0    0 ... 4144 1042  565]
 ...
 [   0    0    0 ... 3616 3963 3582]
 [   0    0    0 ... 3502 1723 1274]
 [   0    0    0 ... 4107 2741 3738]]


In [19]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0, 3138, 4162,  751, 1246,  786,  325, 2901], dtype=int32)

In [20]:
# creating model
embedding_vector_features =40   #dimwnsion of feature vector of embedding 
model=Sequential()

model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.5))
model.add(LSTM(100))  # 1 layer 100 neuron
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))


In [21]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
dropout (Dropout)            (None, 20, 40)            0         
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [23]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(Y)

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X_final, y_final, test_size=0.33, random_state=42)


In [25]:
model.fit(X_train,y_train,validation_data=(X_val,y_val),epochs=10,batch_size=32)


Epoch 1/10
383/383 [==============================] - 6s 9ms/step - loss: 0.2895 - accuracy: 0.8669 - val_loss: 0.1947 - val_accuracy: 0.9162
Epoch 2/10
383/383 [==============================] - 3s 8ms/step - loss: 0.1528 - accuracy: 0.9387 - val_loss: 0.1927 - val_accuracy: 0.9183
Epoch 3/10
383/383 [==============================] - 3s 8ms/step - loss: 0.1168 - accuracy: 0.9571 - val_loss: 0.2068 - val_accuracy: 0.9171
Epoch 4/10
383/383 [==============================] - 3s 8ms/step - loss: 0.0940 - accuracy: 0.9652 - val_loss: 0.2389 - val_accuracy: 0.9200
Epoch 5/10
383/383 [==============================] - 3s 8ms/step - loss: 0.0728 - accuracy: 0.9735 - val_loss: 0.2535 - val_accuracy: 0.9170
Epoch 6/10
383/383 [==============================] - 3s 8ms/step - loss: 0.0613 - accuracy: 0.9782 - val_loss: 0.2689 - val_accuracy: 0.9162
Epoch 7/10
383/383 [==============================] - 3s 8ms/step - loss: 0.0525 - accuracy: 0.9825 - val_loss: 0.2926 - val_accuracy: 0.9171
Epoch 


## Performance Metrics And Accuracy

In [26]:
y_pred=model.predict_classes(X_val)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [27]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
confusion_matrix(y_val,y_pred)

array([[3095,  324],
       [ 210, 2406]])

In [28]:
accuracy_score(y_val,y_pred)

0.9115161557580779

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_val,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.91      0.92      3419
           1       0.88      0.92      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

